name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: aws-laravel-runner

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: cd DogShop && composer install
